# Generated by Django 4.1.7 on 2023-08-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPage',
        ),
    ]
