# Generated by Django 4.1.7 on 2023-08-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_vid_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('lien_video_google_drive', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='vid',
        ),
        migrations.AddField(
            model_name='image',
            name='titre',
            field=models.CharField(default='si', max_length=100),
        ),
    ]
