# Generated by Django 4.1.7 on 2023-08-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_video_delete_vid_image_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='lien_video_google_drive',
            field=models.URLField(blank=True),
        ),
    ]
