# Generated by Django 4.1.7 on 2023-08-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_video_lien_video_google_drive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='lien_video_google_drive',
            new_name='lien',
        ),
    ]
